apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  # namespace: udagram
  labels:
    service: reverseproxy
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: reverseproxy
  type: ClusterIP
